name: demo
on:
  workflow_dispatch:
jobs:
  job:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - run: echo job
  job1:
    runs-on: ubuntu-latest
    if: ${{ 'a' == 'a'}} 
    run: echo job1

    
