name: main

on:
  workflow_dispatch:
  
jobs:
  inputs:
    uses: sark1/Actions/.github/workflows/pipelineconfig.yml@main
    
  compile:
    needs: [inputs]
    if: "contains(needs.inputs.outputs.buildTool, 'maven') && contains(needs.inputs.outputs.language, 'java8')"
    uses: sark1/Actions/.github/workflows/java1_8-maven.yml@main
   
  

  
        
 
