name: main-build
on: 
  workflow_dispatch: 


jobs:
  java1_8-maven:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out 
        uses: actions/checkout@v2
      - name: set up jdk 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
#      - name: build with maven
#        run: mvn -B package --file pom.xml
#      - name: check pwd
#        run: ls -a
#      - name: check target folder 
#        run: |
#          cd target
#          ls -a
  java11-maven:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out 
        uses: actions/checkout@v3
      - name: set up java 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'          
#      - name: build with maven
#        run: mvn -B package --file pom.xml
#      - name: check pwd
#        run: ls -a
#      - name: check target folder 
#        run: |
#          cd target
#          ls -a  
  java17-maven:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
#      - name: Build with Maven
#        run: mvn --batch-mode --update-snapshots package
 
