name: main
on: 
  workflow_call: 
    inputs:
      dockerimage:
        required: true
        type: string
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check
        if: ${{inputs.dockerimage}} == 'java1_8-maven' 
        uses: sark1/Actions/.github/workflows/main-build.yml@main
    
