name: main
on: 
  workflow_dispatch:
jobs:
  do-it:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!
  compile: 
    uses: sark1/Actions/.github/workflows/pipelineconfig.yml@main
    - name: Build
      uses: sark1/Actions/.github/workflows/java11-maven.yml@main
    

  
